# Naming workflow helps understanding what it does
name: Test and Deploy Workflow

# “on” command is where you can mention what triggers a workflow
on:
  push: # Trigger the workflow on all push events
# Run the workflow only on the main branch
    branches: [ main ] 
  pull_request: # Trigger the workflow on pull request events
# Run the workflow only on pull requests targeting the main branch
    branches: [ main ] 
# When the workflow is triggered, some jobs can be automated:
jobs:
  build_and_test:
    name: Build and Test # The name to show up in GitHub logs
    # Similar to Docker, we Specify the operating system for the job
    runs-on: ubuntu-latest # Here the OS is the latest Ubuntu

    # in the following steps, first the code from GitHub repo is fetched
    steps:
      - name: Checkout Repository # Arbitrary name
# Checkout action fetches the repository code (GitHub built-in)
        uses: actions/checkout@v2 
      - name: Set up Node.js # The name to show up in GitHub logs

# Setup-node action sets up a Node.js on the action (GitHub built-in)
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install Dependencies # Install project dependencies
        run: npm install # Run the npm install command to install dependencies

      - name: Run Tests # Run automated tests
        run: npm test # Run the npm test command to execute tests
